version: '3'

services:
  db_dev:
    image: postgres
    container_name: db_dev
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_dev
    volumes:
      - pg:/data/postgres

volumes:
  pg:
    driver: local